Feature/add structure
Monitoring6/monitoring6.github.io pull request #1
Opened 2021-09-16 08:37 UTC by kangyeon0728

made Home page, About page, Culture page, Vision page
Home page is made of HeroSection, Cards, Footer components
About page is made of AboutM6, Footer components
Culture page is made of Member, Footer components
Vision page is made of Ourvision, Footer components.
Vision page and specific design of Culture page is not done yet

2021-09-16 10:44 UTC, sanjuruk requested changes
See the comments

2021-09-16 10:44 UTC, sanjuruk commented on src/components/Footer.js
> +					<small class="website-rights">M6 © 2020</small>
2020? It is 2021!

2021-09-16 10:44 UTC, sanjuruk commented on src/components/Footer.js
> +import ButtonMailto from "./ButtonMailto";
Build fails with this line

2021-09-16 10:47 UTC, kangyeon0728 commented on src/components/Footer.js
> +					<small class="website-rights">M6 © 2020</small>
got it!

2021-09-17 06:30 UTC, kangyeon0728 commented on src/components/Footer.js
> +import ButtonMailto from "./ButtonMailto";
figured it out

2021-09-17 07:02 UTC, merged